# config/routes.yaml

# this route defines the URL (the path to the page) and points to a controller that builds the page
# about-me:
#    path: /about-me
#    controller: App\Controller\LearningController::aboutMe
